# Generated by Django 4.1 on 2022-08-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('slack_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('slack_name', models.CharField(max_length=40)),
                ('steam_id', models.CharField(max_length=40)),
                ('team_id', models.CharField(max_length=40)),
            ],
        ),
    ]
