# Generated by Django 4.1 on 2022-08-13 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('steam_app_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goad.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameSessionPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_joined', models.DateTimeField()),
                ('time_left', models.DateTimeField()),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goad.gamesession')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goad.person')),
            ],
        ),
    ]
