# Generated by Django 4.1 on 2022-08-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goad', '0002_game_gamesession_gamesessionperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gamesessionperson',
            name='time_left',
            field=models.DateTimeField(null=True),
        ),
    ]
