# Generated by Django 4.1 on 2022-08-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goad', '0003_alter_gamesession_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='notified_on',
            field=models.BooleanField(default=False),
        ),
    ]
