# Generated by Django 4.1 on 2022-08-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goad', '0004_gamesession_notified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesessionperson',
            name='notified_on',
            field=models.BooleanField(default=False),
        ),
    ]
