# Generated by Django 4.1 on 2022-08-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goad', '0005_gamesessionperson_notified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='slack_thread_ts',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
